version: "3.8"

services:
  challenge_database:
    image: postgres:10
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: challenge_db
    networks:
      - challenge_network
    ports:
      - 5432:5432

networks:
  challenge_network: